In this notebook, I compare the upper bounds on probablity of
$$
P(|Z| > t)
$$
where $Z~N(0,1)$, using Markov and Mill's inequalities. 
* Markov Inequality:
$$
P(|Z| > t) = P(|Z|^k > t^k)\leq \frac{\mathbb{E}[|Z|^k]}{t^k}
$$
for any positive integer $k$.
$$
$$
* Mill's inequality:
$$
P(|Z| > t) \leq \sqrt{\frac{2}{\pi}}\frac{e^{-t^2/2}}{t}
$$

In [112]:
# Importing packages/
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import norm
%matplotlib inline

In [113]:
# range of t (About 0.05 apart)
t = np.linspace(1,3,50)
t

array([1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
       1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694,
       1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
       1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ,
       1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
       2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347,
       2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
       2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673,
       2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
       2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ])

In [114]:
# Actual probability:
actual_prob = 2 * norm.cdf(-t)
actual_prob

array([0.31731051, 0.2979608 , 0.27941579, 0.26167159, 0.24472188,
       0.22855803, 0.21316926, 0.19854279, 0.184664  , 0.17151659,
       0.15908273, 0.14734328, 0.1362779 , 0.12586525, 0.11608313,
       0.10690866, 0.0983184 , 0.09028855, 0.08279504, 0.07581368,
       0.0693203 , 0.06329083, 0.05770146, 0.05252868, 0.04774941,
       0.04334107, 0.03928163, 0.0355497 , 0.03212457, 0.02898625,
       0.02611551, 0.0234939 , 0.02110379, 0.01892836, 0.01695163,
       0.01515844, 0.01353445, 0.01206614, 0.0107408 , 0.00954651,
       0.00847208, 0.00750711, 0.00664189, 0.00586738, 0.00517525,
       0.00455775, 0.00400775, 0.0035187 , 0.00308455, 0.0026998 ])

In [115]:
Description = []
Description.append('Actual Probability')

In [116]:
# Working on Markov
K = [2,4,6]
Markov_prob = []

for k in K:
    temp_prob = norm.moment(k)/t**k
    Markov_prob.append(temp_prob)
    Description.append('Markov for K = ' + str(k))
len(Markov_prob)

3

In [117]:
Markov_prob[0]

array([1.        , 0.9231065 , 0.85475258, 0.79371901, 0.73899661,
       0.68974433, 0.64525665, 0.60493827, 0.56828402, 0.534863  ,
       0.50430582, 0.47629439, 0.45055357, 0.42684444, 0.40495868,
       0.38471399, 0.36595031, 0.34852664, 0.33231834, 0.31721496,
       0.30311829, 0.28994083, 0.27760435, 0.26603878, 0.25518121,
       0.244975  , 0.23536908, 0.22631728, 0.21777778, 0.20971264,
       0.20208737, 0.19487055, 0.18803352, 0.18155009, 0.1753963 ,
       0.16955017, 0.16399153, 0.15870183, 0.153664  , 0.1488623 ,
       0.14428219, 0.13991026, 0.13573407, 0.13174211, 0.1279237 ,
       0.12426893, 0.12076857, 0.11741405, 0.11419738, 0.11111111])

In [118]:
Description

['Actual Probability',
 'Markov for K = 2',
 'Markov for K = 4',
 'Markov for K = 6']

In [119]:
Mills_prob = np.sqrt(2/np.pi)*np.exp(-t**2/2)/t
Description.append('Mill\'s')

In [120]:
Description

['Actual Probability',
 'Markov for K = 2',
 'Markov for K = 4',
 'Markov for K = 6',
 "Mill's"]

In [121]:
type(actual_prob)

numpy.ndarray

In [122]:
type(Markov_prob)

list

In [123]:
type(Mills_prob)

numpy.ndarray

In [124]:
A = [actual_prob]

In [125]:
A

[array([0.31731051, 0.2979608 , 0.27941579, 0.26167159, 0.24472188,
        0.22855803, 0.21316926, 0.19854279, 0.184664  , 0.17151659,
        0.15908273, 0.14734328, 0.1362779 , 0.12586525, 0.11608313,
        0.10690866, 0.0983184 , 0.09028855, 0.08279504, 0.07581368,
        0.0693203 , 0.06329083, 0.05770146, 0.05252868, 0.04774941,
        0.04334107, 0.03928163, 0.0355497 , 0.03212457, 0.02898625,
        0.02611551, 0.0234939 , 0.02110379, 0.01892836, 0.01695163,
        0.01515844, 0.01353445, 0.01206614, 0.0107408 , 0.00954651,
        0.00847208, 0.00750711, 0.00664189, 0.00586738, 0.00517525,
        0.00455775, 0.00400775, 0.0035187 , 0.00308455, 0.0026998 ])]

In [126]:
for i in Markov_prob:
    A.append(i)

In [127]:
A

[array([0.31731051, 0.2979608 , 0.27941579, 0.26167159, 0.24472188,
        0.22855803, 0.21316926, 0.19854279, 0.184664  , 0.17151659,
        0.15908273, 0.14734328, 0.1362779 , 0.12586525, 0.11608313,
        0.10690866, 0.0983184 , 0.09028855, 0.08279504, 0.07581368,
        0.0693203 , 0.06329083, 0.05770146, 0.05252868, 0.04774941,
        0.04334107, 0.03928163, 0.0355497 , 0.03212457, 0.02898625,
        0.02611551, 0.0234939 , 0.02110379, 0.01892836, 0.01695163,
        0.01515844, 0.01353445, 0.01206614, 0.0107408 , 0.00954651,
        0.00847208, 0.00750711, 0.00664189, 0.00586738, 0.00517525,
        0.00455775, 0.00400775, 0.0035187 , 0.00308455, 0.0026998 ]),
 array([1.        , 0.9231065 , 0.85475258, 0.79371901, 0.73899661,
        0.68974433, 0.64525665, 0.60493827, 0.56828402, 0.534863  ,
        0.50430582, 0.47629439, 0.45055357, 0.42684444, 0.40495868,
        0.38471399, 0.36595031, 0.34852664, 0.33231834, 0.31721496,
        0.30311829, 0.28994083, 0.27760435, 0.

In [128]:
A.append(Mills_prob)

In [129]:
A

[array([0.31731051, 0.2979608 , 0.27941579, 0.26167159, 0.24472188,
        0.22855803, 0.21316926, 0.19854279, 0.184664  , 0.17151659,
        0.15908273, 0.14734328, 0.1362779 , 0.12586525, 0.11608313,
        0.10690866, 0.0983184 , 0.09028855, 0.08279504, 0.07581368,
        0.0693203 , 0.06329083, 0.05770146, 0.05252868, 0.04774941,
        0.04334107, 0.03928163, 0.0355497 , 0.03212457, 0.02898625,
        0.02611551, 0.0234939 , 0.02110379, 0.01892836, 0.01695163,
        0.01515844, 0.01353445, 0.01206614, 0.0107408 , 0.00954651,
        0.00847208, 0.00750711, 0.00664189, 0.00586738, 0.00517525,
        0.00455775, 0.00400775, 0.0035187 , 0.00308455, 0.0026998 ]),
 array([1.        , 0.9231065 , 0.85475258, 0.79371901, 0.73899661,
        0.68974433, 0.64525665, 0.60493827, 0.56828402, 0.534863  ,
        0.50430582, 0.47629439, 0.45055357, 0.42684444, 0.40495868,
        0.38471399, 0.36595031, 0.34852664, 0.33231834, 0.31721496,
        0.30311829, 0.28994083, 0.27760435, 0.

In [130]:
Description

['Actual Probability',
 'Markov for K = 2',
 'Markov for K = 4',
 'Markov for K = 6',
 "Mill's"]

In [131]:
Results = pd.DataFrame({"Method" : Description, "Prob" : A})

In [132]:
Results

Method                                               Prob
0  Actual Probability  [0.31731050786291415, 0.29796080123477753, 0.2...
1    Markov for K = 2  [1.0, 0.9231064975009611, 0.8547525809896759, ...
2    Markov for K = 4  [3.0, 2.5563768171854755, 2.1918059241255374, ...
3    Markov for K = 6  [15.00000000089533, 11.799040250727964, 9.3672...
4              Mill's  [0.48394144903828673, 0.4459956858259848, 0.41...

In [133]:
plt.figure(figsize = (12,12))
plt.grid()
plt.xlabel("t")
plt.ylabel("Probabilty")
plt.ylim([0,1])
plt.xlim([1,3])
Labels = []
for i in range(5):
    plt.plot(t,Results.loc[i,'Prob'])
    Labels.append(Results.loc[i,'Method'])
plt.legend(Labels, ncol = 5, loc = 'upper right')
plt.savefig('UpperBounds.png', dpi = 300)
plt.show()